### ISSUE TITLE
Indication of potential availability of code accompanying the paper?

### ISSUE THREAD

**Issue by wolfiex** [networkgeometry/mercator#1]
Hi, Just wondering if you have an idea of when this is likely to appear?

**Comment by antoineallard** [comment]
Hi, thank you for your interest. The paper is currently under review. The plan is to make the code available upon acceptance. I expect this to be by the end of the summer. I'll reply to this question as soon as I learn more.

**Comment by wolfiex** [comment]
Are there any updates on how far along the review process is?

**Comment by antoineallard** [comment]
The review process is still ongoing. I'll let you know when the code is available as soon as possible

**Comment by wolfiex** [comment]
Ah the wonders of academia - Thanks!

**Comment by antoineallard** [comment]
The paper has been accepted for publication in New Journal of Physics. The code is now available.

**Comment by wolfiex** [comment]
Woo! Thanks for the update and congratulations :-)
