### ISSUE TITLE
Using for link prediction?

### ISSUE THREAD

**Issue by deklanw** [networkgeometry/mercator#2]
Hey, thanks for your library! I have some questions.

Has anyone tried applying this to link prediction? To do so, do I just use equations 3 and 4 from the paper?

Is R-hat in equation 3 the same as "radius_H2" from "filename.inf_coord"?

Making the assumptions above I tested the link prediction performance already, and it seems to do very well (beating most other measures I have).  Just trying to make sure I have everything right.

Thanks!

**Comment by antoineallard** [comment]
Hi, thank you for you interest!

As far as I'm aware, no one used this specific algorithm for link prediction, but you should check directly with the other coauthors ([M. Á. Serrano](http://morfeo.ffn.ub.es/~mariangeles/ws_en/) and [M. Boguñá](http://complex.ffn.ub.es/~mbogunya/)) to make sure.

However, I know that people used other embedding in hyperbolic space techniques for link prediction.

You are right, \hat{R} is the same as radius_H2.

Cheers!
